"""Downloadable report generation (HTML)."""
import html as html_mod
from fastapi import APIRouter, HTTPException
from fastapi.responses import HTMLResponse
from app.services.tasks import task_tracker
from app.utils.cache import get_cached_result

router = APIRouter()


def _build_html_report(report_data):
    r = report_data or {}
    summary = r.get("summary", {}) or {}
    project = r.get("project", {}) or {}
    metrics = r.get("metrics", {}) or {}
    smells = r.get("smells", {}) or {}
    ai = r.get("ai_analysis") or {}
    health = r.get("health_score", 0)
    grade = r.get("grade", "N/A")
    pn = html_mod.escape(project.get("project_name", "Repo"))
    now_str = __import__("datetime").datetime.now().strftime("%Y-%m-%d %H:%M")

    def li(items):
        if not items:
            return "<li>None</li>"
        return "".join(f"<li>{html_mod.escape(str(i))}</li>" for i in items)

    ai_html = ""
    if ai:
        ai_hs = ai.get("ai_health_score", "N/A")
        ai_g = ai.get("ai_grade", "N/A")
        ai_m = html_mod.escape(ai.get("model_used", "N/A"))
        ai_es = html_mod.escape(ai.get("executive_summary", ""))
        ai_html = "<h2>AI Insights</h2><table>"
        ai_html += f"<tr><td>AI Health</td><td>{ai_hs}/100</td></tr>"
        ai_html += f"<tr><td>AI Grade</td><td>{ai_g}</td></tr>"
        ai_html += f"<tr><td>Model</td><td>{ai_m}</td></tr>"
        ai_html += "</table>"
        ai_html += f"<p>{ai_es}</p>"
        ai_html += "<ul>" + li(ai.get("strengths")) + "</ul>"

    total_files = metrics.get("total_files", project.get("total_files", 0))
    code_lines = metrics.get("total_code_lines", 0)
    cr = metrics.get("comment_ratio", 0) * 100
    cx = metrics.get("total_complexity", 0)
    lang = html_mod.escape(project.get("primary_language", "N/A"))
    arch_type = html_mod.escape(r.get("architecture", {}).get("architecture_type", "N/A"))
    frameworks = ", ".join(project.get("frameworks", [])) or "None"
    repo_type = html_mod.escape(project.get("repository_type", "N/A"))

    return f"""<!DOCTYPE html><html lang="en">
<head><meta charset="UTF-8"><title>EngineerOS Report - {pn}</title>
<style>
body{{font-family:'Segoe UI',sans-serif;max-width:1000px;margin:0 auto;padding:32px 24px;color:#1e293b;background:#f8fafc;line-height:1.6}}
h1{{font-size:28px}}h2{{font-size:20px;margin-top:28px;border-bottom:2px solid #e2e8f0}}
.sc{{background:linear-gradient(135deg,#0ea5e9,#10b981);color:#fff;padding:20px;border-radius:12px;margin-bottom:24px}}
.sc .b{{font-size:48px;font-weight:800}}
.g{{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin-bottom:24px}}
.c{{background:#fff;border-radius:10px;padding:16px;box-shadow:0 1px 3px rgba(0,0,0,0.08)}}
.c .v{{font-size:24px;font-weight:700}}ul{{padding-left:20px}}
table{{width:100%;border-collapse:collapse;margin:12px 0}}
th,td{{padding:8px 12px;text-align:left;border-bottom:1px solid #e2e8f0}}
th{{background:#f1f5f9}}.f{{margin-top:40px;text-align:center;color:#94a3b8;font-size:12px}}
</style></head><body>
<h1>EngineerOS Engineering Report</h1>
<p><strong>Repository:</strong> {pn} | <strong>Generated:</strong> {now_str} | <strong>Type:</strong> {repo_type}</p>
<div class="sc"><div style="display:flex;justify-content:space-between;align-items:center">
<div><div style="font-size:14px;opacity:.8">Engineering Health</div><div class="b">{health}/100</div></div>
<div style="font-size:64px;font-weight:800;opacity:.9">{grade}</div></div></div>
<div class="g">
<div class="c"><strong>Files</strong><br><span class="v">{total_files}</span></div>
<div class="c"><strong>Code Lines</strong><br><span class="v">{code_lines:,}</span></div>
<div class="c"><strong>Architecture</strong><br><strong style="font-size:16px">{arch_type}</strong></div>
<div class="c"><strong>Language</strong><br><strong style="font-size:16px">{lang}</strong></div>
<div class="c"><strong>Comment Ratio</strong><br><span class="v">{cr:.1f}%</span></div>
<div class="c"><strong>Complexity</strong><br><span class="v">{cx}</span></div></div>
<h2>Executive Summary</h2>
<p>{html_mod.escape(summary.get("executive_summary", ""))}</p>
{ai_html}
<h2>Strengths</h2><ul>{li(summary.get("strengths"))}</ul>
<h2>Risks</h2><ul>{li(summary.get("risks"))}</ul>
<h2>Recommendations</h2><ul>{li(summary.get("recommendations"))}</ul>
<h2>Frameworks</h2><p>{html_mod.escape(frameworks)}</p>
<div class="f">Generated by EngineerOS</div>
</body></html>"""


@router.get("/{task_id}", response_class=HTMLResponse)
async def download_report(task_id: str):
    task = task_tracker.get_task(task_id)
    if not task:
        cached = get_cached_result(task_id)
        if cached:
            task = {"status": "completed", "result": cached}
        else:
            raise HTTPException(status_code=404, detail="Task not found.")
    if task["status"] != "completed" or not task.get("result"):
        raise HTTPException(status_code=400, detail="Task not completed.")
    html = _build_html_report(task["result"])
    return HTMLResponse(
        content=html,
        headers={"Content-Disposition": f'attachment; filename="engineeros-report-{task_id[:8]}.html"'},
    )
